### ISSUE TITLE
Task fails with NPE

### ISSUE THREAD

**Issue by paplorinc** [reyerizo/jcstress-gradle-plugin#27]
Similarly to https://github.com/jerzykrlk/jcstress-gradle-plugin/issues/20#issue-443139669, having a kotlin build script with:
```kotlin
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath("com.github.erizo.gradle:jcstress-gradle-plugin:0.8.4")
    }
}

repositories {
    jcenter()
}

apply(plugin = "jcstress")
```
and [APISample_02_Arbiters](https://hg.openjdk.java.net/code-tools/jcstress/file/e819ba0c3a59/jcstress-samples/src/main/java/org/openjdk/jcstress/samples/APISample_02_Arbiters.java) under `src/jcstress/java` and running `./gradlew jcstress` using latest Gradle 6.7 fails with:
```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:167)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at org.openjdk.jcstress.infra.runners.TestList.getTests(TestList.java:53)
        at org.openjdk.jcstress.infra.runners.TestList.tests(TestList.java:105)
        at org.openjdk.jcstress.JCStress.getTests(JCStress.java:139)
        at org.openjdk.jcstress.JCStress.run(JCStress.java:67)
        at org.openjdk.jcstress.Main.main(Main.java:60)
```

**Comment by jerzykrlk** [comment]
Hey Pap,

I'm afraid it's not something I can pick up right away. Especially, that I've never used a Kotlin-Gradle project.

But, would you be able to confirm that this happens with both Groovy and Kotlin scripts? And, is only this specific test case affected, or all JCStress suites result in the same error?

Thank you!
Jerzy

**Comment by paplorinc** [comment]
Shouldn't depend on Kotlin, could you please just try your plugin with latest Gradle?

**Comment by jerzykrlk** [comment]
I've tried to reproduce the issue with an integration test: https://github.com/jerzykrlk/jcstress-gradle-plugin/pull/30/files

Seems to be working fine with Gradle 6.6.1 (I couldn't find Gradle 6.7 anywhere) and Groovy config.

I will keep looking for the problem, though. No worries.

**Comment by paplorinc** [comment]
Could you maybe try it with https://gradle.org/release-candidate?
If you can't reproduce it, I'll try to come up with a simple reproducer in the next few weeks.

**Comment by jerzykrlk** [comment]
I assume it's just a matter of setting the right version string, I just
entered "6.7", which failed.

I will try to update the integration test soon - maybe just it will do the
trick.

Thank you!

pon., 28 wrz 2020, 21:59 użytkownik Lőrinc Pap <notifications@github.com>
napisał:

**Comment by jerzykrlk** [comment]
I've tried to create a Gradle kts integration test case, but I failed miserably (see here: https://github.com/jerzykrlk/jcstress-gradle-plugin/pull/30/commits/0c07caa7177b4ad150ab73160dd1187dd6bb9875) - the test case won't find the plugin.
Groovy-based Gradle 6.7-rc2 seems fine, though - this will need more investigation.

**Comment by jerzykrlk** [comment]
Hi Pap, 

I had a little time to produce a kts build file: https://github.com/jerzykrlk/jcstress-gradle-plugin/pull/30 - apparently the Gradle build works well. 

Would you be able to verify the problem with the recent 0.8.6 version of the plugin? 
I noticed some changes that could fix your issue, too.

**Comment by paplorinc** [comment]
Will do, thank you!

**Comment by jerzykrlk** [comment]
I've recreated the entire setup (Gradle 6.7-rc2, the Arbiters class and build.gradle.kts) and no results.

Please have a look here: https://github.com/jerzykrlk/jcstress-kotlin-project - I will need some extra help reproducing the issue (like - what JVM you used, what operating system, etc). My setup is a Windows machine, AdoptOpenJDK 11 and everything works fine here.

Thanks!

**Comment by anti-social** [comment]
Also have the same problem. And I managed to reproduce it. My problem is `kapt`:
https://github.com/anti-social/jcstress-with-kapt

If you comment one line https://github.com/anti-social/jcstress-with-kapt/blob/master/build.gradle.kts#L22 then `jcstress` will work again.

**Comment by anti-social** [comment]
Gradle version: `6.6.1`
Java: `14.0.2` & `11.0.8`

With `kapt` plugin active there is no `META-INF/TestList` (as I can see NPE is a result of missing this file) in the resulting jar file.
`*_jcstress.class` and `jcstress` dependency classes is also missing.

**Comment by jerzykrlk** [comment]
Hey @anti-social - sorry, it's been a while. 

Kapt seems to be an annotation processor for Kotlin - it might conflict with the JDK's annotation processor used in jcstress.

**Comment by jerzykrlk** [comment]
I think I've fixed the issue. You were right - that was kapt causing the damage.

**Comment by anti-social** [comment]
Thanks a lot for your work.

**Comment by jerzykrlk** [comment]
Hey @anti-social - I've just published a new version - 0.8.7. See https://github.com/jerzykrlk/jcstress-gradle-plugin/releases/tag/0.8.7

**Comment by wind57** [comment]
same problem happens for gradle 7.4 and 0.8.13 plugin version

**Comment by jerzykrlkroche** [comment]
Hi @wind57 Thank you for the report. Apologies for the delay - I'll try to pick this up next week. 

Can you send your Java version, too?

Thanks!

**Comment by wind57** [comment]
sure! its jdk-17, thank you

**Comment by jerzykrlk** [comment]
Hey @wind57 - Gradle 7 seems to contain quite a few API changes making it incompatible with the current plugin version. No worries though - I'll try to fix it.

**Comment by wind57** [comment]
Thank you!

**Comment by jerzykrlk** [comment]
Ok, some progress is there - the tool works with Gradle 7.5.1, but not with Java 17. 

The Gradle-related changes are in master - but I think existing plugin should work, too.

**Comment by wind57** [comment]
I can provide a sample github repo. will that help? the test is really easy, actually, nothing unusual.

**Comment by jerzykrlk** [comment]
Hi @wind57 yes, that's exactly what I need. I wasn't able to reproduce the issue in my current test suite - I hope to find something in yours.

Thank you!

**Comment by Spikhalskiy** [comment]
Hi @jerzykrlk, I faced the same problem. Please find a repro attached, to reproduce it's enough to run `./gradlew jcstress`
[reproduction.zip](https://github.com/reyerizo/jcstress-gradle-plugin/files/10800118/reproduction.zip)

**Comment by jerzykrlk** [comment]
Hello Spikhalskiy,

I think I've found the reason. Please move the jcstress test to the jcstress sourceset. Have a look here:

![jcstress-sourceset](https://user-images.githubusercontent.com/4005877/220742924-5da3b671-6a65-4230-a259-4684538e0fd5.png)

I think it's due to JCStress internals. I'll need to figure out a good way to communicate this to the users.

Have a good day.

**Comment by Spikhalskiy** [comment]
This totally makes sense. I think any combination of 
- adding this into the plugin's Readme and 
- making the plugin make an explicit check of the source sets and return a meaningful error instead of the null pointer
would be great

**Comment by jerzykrlk** [comment]
I just made an extra check - you could work around that by adding jsctress as an annotation processor like that:

![jcstress-apt](https://user-images.githubusercontent.com/4005877/220750187-cd2df69b-23c5-495c-b408-ec4536e7e4f1.png)

I'll need to fix the docs anyway - the paragraph about a separate sourceset is well hidden at the end of the readme. Adding a code check will be trickier - but I'll try to think of something.

Thanks for your help - especially for the example!
